
package com.teamsystem.hub.b2b.soap.read.v7;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.10
 * 2018-10-28T14:46:11.652+01:00
 * Generated source version: 3.1.10
 */

@WebFault(name = "validationException", targetNamespace = "http://schema.read.b2b.hub.teamsystem.com/v7")
public class ValidationExceptionMsg extends Exception {
    
    private com.teamsystem.hub.b2b.soap.read.v7.ValidationException validationException;

    public ValidationExceptionMsg() {
        super();
    }
    
    public ValidationExceptionMsg(String message) {
        super(message);
    }
    
    public ValidationExceptionMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public ValidationExceptionMsg(String message, com.teamsystem.hub.b2b.soap.read.v7.ValidationException validationException) {
        super(message);
        this.validationException = validationException;
    }

    public ValidationExceptionMsg(String message, com.teamsystem.hub.b2b.soap.read.v7.ValidationException validationException, Throwable cause) {
        super(message, cause);
        this.validationException = validationException;
    }

    public com.teamsystem.hub.b2b.soap.read.v7.ValidationException getFaultInfo() {
        return this.validationException;
    }
}
